# -*- coding: utf-8 -*-
"""Text Summarization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16e2ZGKViioDLwlJRFjgWPX4XheXJx906
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import pickle as pkl
import matplotlib.pyplot as plt
# %matplotlib inline

import re
import nltk
from nltk import WordNetLemmatizer 
from nltk.corpus import wordnet
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

from keras.preprocessing.text import Tokenizer 
from keras.preprocessing.sequence import pad_sequences
from nltk.corpus import stopwords

# %tensorflow_version 2.x
import tensorflow as tf
from tensorflow.keras.layers import Input, LSTM, Embedding, Dense, Concatenate, TimeDistributed, Bidirectional, Attention
from tensorflow.keras.models import Model

"""Using Libaries"""

!pip install bert-extractive-summarizer

!pip install transformers==2.2.0

!pip install spacy==2.0.12

from summarizer import Summarizer,TransformerSummarizer

body='''         Eight people are dead following two shootings at shisha bars in the western German city of Hanau. At least five people were injured after gunmen opened fire at about 22:00 local time (21:00 GMT), police told the BBC. Police added that they are searching for the suspects, who fled the scene and are currently at large. The first shooting was at a bar in the city centre, while the second was in Hanau's Kesselstadt neighbourhood, according to local reports. Police officers and helicopters are patrolling both areas. An unknown number of gunmen killed three people at the first shisha bar, Midnight, before driving to the Arena Bar & Cafe and shooting dead another five victims, regional broadcaster Hessenschau reports. A dark-coloured vehicle was then seen leaving the scene.The motive for the attack is unclear, a police statement said. Can-Luca Frisenna, who works at a kiosk at the scene of one of the shootings said his father and brother were in the area when the attack took place. It's like being in a film, it's like a bad joke, that someone is playing a joke on us, he told Reuters.I can't grasp yet everything that has happened. My colleagues, all my colleagues, they are like my family - they can't understand it either. Hanau, in the state of Hessen, is about 25km (15 miles) east of Frankfurt. It comes four days after another shooting in Berlin, near a Turkish comedy show at the Tempodrom concert venue, which killed one person.'''

bert_model = Summarizer()

bert_summary = ''.join(bert_model(description[0], min_length=60))
print(bert_summary)

len(bert_summary.split())

GPT2_model = TransformerSummarizer(transformer_type="GPT2",transformer_model_key="gpt2-medium")

full = ''.join(GPT2_model(description[1],num_sentences=0,use_first=True))
print(full)

heading[1]

import pandas as pd

merchant = pd.read_html("http://shakespeare.mit.edu/merchant/full.html")[0]

merchant.head()

!wget https://getfreestorybooks.weebly.com/uploads/1/0/7/7/107718885/2_-_artemis_fowl_and_the_arctic_incident.pdf



julius = removeSpecialCharacters(julius)
julius

full = ''.join(GPT2_model(julius))

print(full,file=open('hamlet-gpt2.txt','w'))

len(full.split())

julius=''' 

'''

bert_summary = ''.join(bert_model(julius))
print(bert_summary)

len(bert_summary.split())

len(julius.split())

